

::: {.callout-warning}
This site is a very early beta version and will change significantly over the coming months. This may continue until I finish my DPhil in October 2025, at which time it will (for better or worse) become relatively static.

There are some quirks with the current hosting platform. Some website elements, such as links between chapters, are not presenting properly. These will be automatically fixed when the website is made public on GitHub pages.
:::

## Welcome {.unnumbered}

Renewal models are popular in statistical epidemiology for their use as a semi-mechanistic model of disease transmission. We demonstrate how sequential Monte Carlo (SMC) methods can be used to perform inference on and forecast with these models.

With these methods one can:

- Estimate $R_t$ from imperfect data, or from multiple sources of data
- Produce well-calibrated short-term forecasts
- Estimate abrupt change-points in disease transmission
- ... and so much more

Our approach:

- Is simple, intuitive, and flexible
- Produces valid credible intervals on quantities of interest
- Can **simultaneously** account for reporting biases, aggregated/missing data, imported cases, multiple data sources, and more.

![Reported cases for the first 100 days of the COVID-19 pandemic in Aotearoa New Zealand [CITE]. We will develop methods to estimate the reproduction number from these data.](images/root_readme_data.png)

Renewal models underlie many of the most popular methods for reproduction number estimation, including EpiEstim [@coriNewFrameworkSoftware2013] and EpiNow2 [@abbottEstimatingTimevaryingReproduction2020]. They have also been used to model elimination probabilities [@paragDecipheringEarlywarningSignals2021], estimate the effect of non-pharmaceutical interventions [@flaxmanEstimatingEffectsNonpharmaceutical2020], and produce forecasts [@banholzerComparisonShorttermProbabilistic2023], for example.

## Structure of this book

This book is made up of a collection of Jupyter-style notebooks. All code is implemented in [Julia](https://julialang.org/), a programming language with the speed of C++ and simplicity of R and Python. The notebooks are organised into chapters:

- **Introduction:** We introduce key concepts such as the [renewal model](introduction.html) or [hidden-state models](link.link). Those already familiar with these concepts can safely skip these pages.
- **Sequential Monte Carlo:** We introduce specific SMC methods. This includes defining the [bootstrap filter](link.link) and [particle marginal Metropolis Hastings](link.link).
- **Evaluation:** We introduce key metrics for model evaluation, including [scoring rules](link.link), [KL-divergence](link.link), and ???.
- **Reproduction number estimation:** A collection of $R_t$ estimators, accounting for various statistical artefacts, are introduced. 
- **Additional models:** We demonstrate how these methods can be used for [epidemic forecasting](link.link), [inference](link.link), and [elimination probabilities](link.link).
- **Case studies:**
- **Other methods:** We compare our methods to popular alternatives in the literature. Where possible, Julia implementations are provided for these.




## Using Julia

We recognise that Julia is not widely used in epidemiology. While we would love to implement our methods in R, they would be extremely slow without a C++ backend. Instead, our methods are all natively implemented in Julia and require no external software - making the entire process much simpler!

Getting started with Julia is easy (see below) and our examples are written for those with no prior knowledge of the language.

## Getting started

We do not use any external dependencies, so you can run all code in this repository with a standard Julia installation. To get started, all you need to do is:

1. Install Julia from [julialang.org](https://julialang.org/downloads/)
2. Clone this repository
3. Start Julia in your terminal and run:

```julia
using Pkg
Pkg.add("IJulia")
using IJulia
notebook()
```

This will open a Jupyter notebook in your browser. Navigate to the GitHub repository and open `main.ipynb` to get started.

*Alternatively, you can open the cloned repository in VS Code (or your preferred IDE) and run the notebooks this way. If using VS Code, we recommend installing the [Julia extension](link.link).*

### GitHub layout

The files and folders you should care about:

- `/notebooks/`: Contains the main tutorial notebooks
- `/src/`: Contains important source code
- `/data/`: Contains all example data used in the tutorial

You can ignore (but feel free to explore):

- `/paper/`: Scripts and outputs associated with the [accompanying paper](link.link)
- `/docs/`: Contains the rendered tutorial
- `/site/`: Contains the quarto website files (these are rendered to `/docs/`)
- `/assets/`: Contains images and other assets used in the tutorials and readme files
- and files like `.gitignore` and `.nojekyll` which are for repo management

